name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Easy Minecraft Server Gui.sln
      Test_Project_Path: Easy Minecraft Server Gui\Easy Minecraft Server Gui.csproj
      Output_Directory: ./output

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Create output directory
      run: mkdir -p ${{ env.Output_Directory }}

    - name: Build the project
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} /p:OutputPath=${{ env.Output_Directory }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Copy additional files
      run: |
        cp src/connect.bat ${{ env.Output_Directory }}
        cp src/help1.png ${{ env.Output_Directory }}
        cp src/help2.png ${{ env.Output_Directory }}
        cp src/help3.png ${{ env.Output_Directory }}
        cp src/serverOpen.bat ${{ env.Output_Directory }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ env.Output_Directory }}/*
        if-no-files-found: warn
